# Generated by Django 6.0.7 on 2026-07-13 23:11

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="nombre del evento"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("boda", "Boda"),
                            ("corporativo", "Evento corporativo"),
                            ("cumpleanos", "Cumpleaños"),
                            ("social", "Evento social"),
                            ("otro", "Otro"),
                        ],
                        default="boda",
                        max_length=20,
                        verbose_name="tipo de evento",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=200, verbose_name="cliente"),
                ),
                (
                    "client_phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="teléfono del cliente"
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo del cliente"
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="país"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=120, verbose_name="ciudad"),
                ),
                (
                    "venue_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="espacio / lugar principal",
                    ),
                ),
                (
                    "venue_address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="dirección"
                    ),
                ),
                ("event_date", models.DateField(verbose_name="fecha del evento")),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="hora de inicio"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="hora de fin"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planificacion", "En planificación"),
                            ("confirmado", "Confirmado"),
                            ("en_curso", "En curso"),
                            ("finalizado", "Finalizado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="planificacion",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="accounts.company",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "planner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_planned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="planificador a cargo",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento",
                "verbose_name_plural": "eventos",
                "ordering": ["-event_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="EventSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="actividad")),
                (
                    "venue_name",
                    models.CharField(blank=True, max_length=200, verbose_name="lugar"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="dirección"
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="hora de inicio")),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="hora de fin"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="orden")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "actividad del itinerario",
                "verbose_name_plural": "itinerario",
                "ordering": ["order", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="EventTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_in_event",
                    models.CharField(
                        choices=[
                            ("planner", "Planificador"),
                            ("supervisor", "Supervisor"),
                            ("encargado", "Encargado"),
                        ],
                        default="encargado",
                        max_length=20,
                        verbose_name="rol en el evento",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        help_text="Ej. Banquete, Sonido, Decoración, Logística",
                        max_length=120,
                        verbose_name="área / responsabilidad",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="asignado desde"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
                (
                    "reports_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        to="events.eventteammember",
                        verbose_name="reporta a",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "miembro del equipo del evento",
                "verbose_name_plural": "equipo del evento",
                "ordering": ["role_in_event", "area"],
                "unique_together": {("event", "user")},
            },
        ),
    ]
