# Generated by Django 6.0.7 on 2026-07-18 20:33

import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="nombre del evento"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("boda", "Boda"),
                            ("corporativo", "Evento corporativo"),
                            ("cumpleanos", "Cumpleaños"),
                            ("social", "Evento social"),
                            ("otro", "Otro"),
                        ],
                        default="boda",
                        max_length=20,
                        verbose_name="tipo de evento",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=200, verbose_name="cliente"),
                ),
                (
                    "client_phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="teléfono del cliente"
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo del cliente"
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="país"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=120, verbose_name="ciudad"),
                ),
                (
                    "venue_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="espacio / lugar principal",
                    ),
                ),
                (
                    "venue_address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="dirección"
                    ),
                ),
                ("event_date", models.DateField(verbose_name="fecha del evento")),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="hora de inicio"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="hora de fin"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planificacion", "En planificación"),
                            ("confirmado", "Confirmado"),
                            ("en_curso", "En curso"),
                            ("finalizado", "Finalizado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="planificacion",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "share_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador usado para el link público (sin login) del planograma del cortejo.",
                        unique=True,
                        verbose_name="token para compartir",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="accounts.company",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "planner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_planned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="planificador a cargo",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento",
                "verbose_name_plural": "eventos",
                "ordering": ["-event_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="EventSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("ceremonia", "Ceremonia"),
                            ("recepcion", "Recepción"),
                            ("montaje", "Montaje"),
                            ("desmontaje", "Desmontaje"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        help_text="Para agrupar el itinerario en reportes: ceremonia, recepción, montaje, desmontaje",
                        max_length=20,
                        verbose_name="sección",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="actividad")),
                (
                    "venue_name",
                    models.CharField(blank=True, max_length=200, verbose_name="lugar"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="dirección"
                    ),
                ),
                ("date", models.DateField(verbose_name="fecha")),
                ("start_time", models.TimeField(verbose_name="hora de inicio")),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="hora de fin"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="orden")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "actividad del itinerario",
                "verbose_name_plural": "itinerario",
                "ordering": ["date", "order", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="MealCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("equipo", "Equipo interno"),
                            ("proveedores", "Proveedores"),
                        ],
                        default="equipo",
                        max_length=20,
                        verbose_name="grupo",
                    ),
                ),
                (
                    "meal_label",
                    models.CharField(
                        help_text="Ej. Almuerzo, Cena, Snack box",
                        max_length=100,
                        verbose_name="comida",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(default=0, verbose_name="cantidad"),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notas"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_counts",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "conteo de comida",
                "verbose_name_plural": "comidas de equipo y proveedores",
                "ordering": ["group", "meal_label"],
            },
        ),
        migrations.CreateModel(
            name="ProcessionalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="orden de entrada"
                    ),
                ),
                (
                    "left_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="lado izquierdo"
                    ),
                ),
                (
                    "right_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="lado derecho"
                    ),
                ),
                (
                    "detail",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="detalle"
                    ),
                ),
                (
                    "music",
                    models.CharField(blank=True, max_length=255, verbose_name="música"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processional_entries",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "entrada del cortejo",
                "verbose_name_plural": "orden del cortejo (planograma)",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WeddingPartyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "list_type",
                    models.CharField(
                        choices=[
                            ("boutonniere", "Boutonnieres"),
                            ("bridesmaid", "Damas"),
                            ("speaker", "Discursos"),
                        ],
                        max_length=20,
                        verbose_name="lista",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="cantidad"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nombre")),
                (
                    "role_description",
                    models.CharField(
                        blank=True,
                        help_text="Ej. 'Corte', 'FATHER OF THE GROOM', 'ROBERT BROTHER'S'",
                        max_length=150,
                        verbose_name="rol / descripción",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="orden")),
                (
                    "table_number",
                    models.CharField(blank=True, max_length=20, verbose_name="mesa"),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notas"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wedding_party_members",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "miembro del cortejo",
                "verbose_name_plural": "cortejo nupcial",
                "ordering": ["list_type", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="EventTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        help_text="Ej. Banquete, Sonido, Decoración, Logística",
                        max_length=120,
                        verbose_name="área / responsabilidad",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="asignado desde"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
                (
                    "reports_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        to="events.eventteammember",
                        verbose_name="reporta a",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_memberships",
                        to="accounts.role",
                        verbose_name="rol",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "miembro del equipo del evento",
                "verbose_name_plural": "equipo del evento",
                "ordering": ["role__name", "area"],
                "unique_together": {("event", "user")},
            },
        ),
    ]
