# Generated by Django 6.0.7 on 2026-07-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="processionalentry",
            options={
                "ordering": ["phase", "order"],
                "verbose_name": "entrada del cortejo",
                "verbose_name_plural": "orden del cortejo (planograma)",
            },
        ),
        migrations.AddField(
            model_name="processionalentry",
            name="center_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="centro"),
        ),
        migrations.AddField(
            model_name="processionalentry",
            name="phase",
            field=models.CharField(
                choices=[("entrada", "Entrada"), ("salida", "Salida")],
                default="entrada",
                max_length=10,
                verbose_name="fase",
            ),
        ),
    ]
