# Generated by Django 6.0.7 on 2026-07-19 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("events", "0002_alter_processionalentry_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mealcount",
            options={
                "ordering": ["group", "target_name", "meal_label"],
                "verbose_name": "conteo de comida",
                "verbose_name_plural": "comidas de equipo y proveedores",
            },
        ),
        migrations.AlterModelOptions(
            name="weddingpartymember",
            options={
                "ordering": ["list_type__order", "order", "name"],
                "verbose_name": "miembro del cortejo",
                "verbose_name_plural": "cortejo nupcial",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="civil_ceremony_venue",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="lugar de la ceremonia civil"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="cocktail_venue",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="lugar del cóctel"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="religious_ceremony_venue",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="lugar de la ceremonia eclesiástica",
            ),
        ),
        migrations.AddField(
            model_name="mealcount",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="monto"
            ),
        ),
        migrations.AddField(
            model_name="mealcount",
            name="target_name",
            field=models.CharField(
                blank=True,
                help_text="Ej. 'Transportes', 'Asistente 1', 'Planner'",
                max_length=150,
                verbose_name="proveedor / persona",
            ),
        ),
        migrations.AddField(
            model_name="processionalentry",
            name="detail_visible_public",
            field=models.BooleanField(
                default=True,
                help_text="Desactívalo si esta nota es solo para uso interno del equipo de planificación.",
                verbose_name="mostrar el detalle en el enlace público",
            ),
        ),
        migrations.AlterField(
            model_name="mealcount",
            name="group",
            field=models.CharField(
                choices=[
                    ("equipo", "Equipo interno"),
                    ("proveedores", "Proveedores"),
                    ("imprevistos", "Imprevistos"),
                ],
                default="equipo",
                max_length=20,
                verbose_name="grupo",
            ),
        ),
        migrations.CreateModel(
            name="WeddingPartyListType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="nombre de la lista"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="orden")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wedding_party_list_types",
                        to="accounts.company",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "lista del cortejo",
                "verbose_name_plural": "mantenimiento de listas del cortejo",
                "ordering": ["order", "name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.AlterField(
            model_name="weddingpartymember",
            name="list_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="events.weddingpartylisttype",
                verbose_name="lista",
            ),
        ),
    ]
