# Generated by Django 6.0.7 on 2026-07-20 02:20

import apps.events.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_eventsectiontype_and_migrate_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="advance_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monto de anticipo recibido del cliente para gastos del evento (puede ser 0).",
                max_digits=12,
                verbose_name="anticipo",
            ),
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="fecha")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="descripción"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="monto"
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        help_text="Factura, recibo u otro comprobante (opcional).",
                        null=True,
                        upload_to=apps.events.models.expense_document_upload_path,
                        verbose_name="documento",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses_recorded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registrado por",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "gasto",
                "verbose_name_plural": "gastos del evento",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "realization_date",
                    models.DateField(verbose_name="fecha de realización"),
                ),
                (
                    "client_name",
                    models.CharField(max_length=200, verbose_name="cliente"),
                ),
                (
                    "activity",
                    models.CharField(max_length=200, verbose_name="actividad"),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=1,
                        max_digits=10,
                        verbose_name="tasa de cambio",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizada"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotations_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creada por",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotations",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "cotización",
                "verbose_name_plural": "cotizaciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuotationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendor_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="proveedor"
                    ),
                ),
                (
                    "detail",
                    models.CharField(max_length=255, verbose_name="detalle / item"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="cantidad"),
                ),
                (
                    "value_dop",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="valor (DOP)",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="orden")),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="events.quotation",
                        verbose_name="cotización",
                    ),
                ),
            ],
            options={
                "verbose_name": "línea de cotización",
                "verbose_name_plural": "líneas de cotización",
                "ordering": ["order", "id"],
            },
        ),
    ]
