# Generated by Django 6.0.7 on 2026-07-20 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_event_advance_amount_expense_quotation_quotationitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(max_length=30, verbose_name="número de factura"),
                ),
                ("date", models.DateField(verbose_name="fecha")),
                (
                    "issuer_name",
                    models.CharField(
                        max_length=200, verbose_name="nombre de quien factura"
                    ),
                ),
                (
                    "issuer_contact",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="correo / teléfono"
                    ),
                ),
                (
                    "bill_to_name",
                    models.CharField(max_length=200, verbose_name="facturar a"),
                ),
                (
                    "bill_to_attn",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="atención de"
                    ),
                ),
                (
                    "bill_to_city",
                    models.CharField(blank=True, max_length=150, verbose_name="ciudad"),
                ),
                (
                    "bill_to_country",
                    models.CharField(blank=True, max_length=150, verbose_name="país"),
                ),
                (
                    "job_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="trabajo / evento"
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="términos de pago"
                    ),
                ),
                (
                    "payment_instructions",
                    models.TextField(blank=True, verbose_name="instrucciones de pago"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizada"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creada por",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "factura",
                "verbose_name_plural": "facturas",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="descripción"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="monto"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="orden")),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="events.invoice",
                        verbose_name="factura",
                    ),
                ),
            ],
            options={
                "verbose_name": "línea de factura",
                "verbose_name_plural": "líneas de factura",
                "ordering": ["order", "id"],
            },
        ),
    ]
