# Generated by Django 6.0.7 on 2026-07-21 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_invoice_and_invoiceitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="advance_amount",
        ),
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[("vigente", "Vigente"), ("anulada", "Anulada")],
                default="vigente",
                max_length=10,
                verbose_name="estado",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="voided_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="anulada el"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="voided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices_voided",
                to=settings.AUTH_USER_MODEL,
                verbose_name="anulada por",
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="correlative",
            field=models.PositiveIntegerField(default=0, verbose_name="correlativo"),
        ),
        migrations.CreateModel(
            name="EventAdvance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="fecha")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="monto"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="nota"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advances_recorded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registrado por",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advances",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "anticipo",
                "verbose_name_plural": "anticipos del evento",
                "ordering": ["-date", "-id"],
            },
        ),
    ]
