# Generated by Django 6.0.7 on 2026-07-21 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_company_date_format_settings"),
        ("events", "0007_advances_correlative_invoice_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeatingTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_number",
                    models.CharField(max_length=20, verbose_name="número de mesa"),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=8, verbose_name="capacidad (personas)"
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notas"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seating_tables",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "mesa",
                "verbose_name_plural": "plan de mesas",
                "ordering": ["table_number"],
            },
        ),
        migrations.CreateModel(
            name="TableGuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nombre")),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notas"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="orden")),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="events.seatingtable",
                        verbose_name="mesa",
                    ),
                ),
            ],
            options={
                "verbose_name": "invitado",
                "verbose_name_plural": "invitados",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="WeddingTableType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nombre")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="orden")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_types",
                        to="accounts.company",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "tipo de mesa",
                "verbose_name_plural": "mantenimiento de tipos de mesa",
                "ordering": ["order", "name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.AddField(
            model_name="seatingtable",
            name="table_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tables",
                to="events.weddingtabletype",
                verbose_name="tipo de mesa",
            ),
        ),
    ]
