# Generated by Django 6.0.7 on 2026-07-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_seating_chart"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="currency",
            field=models.CharField(
                blank=True, default="USD", max_length=10, verbose_name="moneda"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="currency_symbol",
            field=models.CharField(
                blank=True, default="$", max_length=5, verbose_name="signo de moneda"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_received",
            field=models.BooleanField(default=False, verbose_name="pago recibido"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_received_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="fecha de pago recibido"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="show_currency_symbol",
            field=models.BooleanField(
                default=False,
                help_text="Por defecto el signo no se muestra en los montos, solo si se activa aquí.",
                verbose_name="mostrar signo de moneda",
            ),
        ),
    ]
