# Generated by Django 6.0.7 on 2026-07-21 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0009_invoice_currency_and_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="tableguest",
            name="gives_speech",
            field=models.BooleanField(default=False, verbose_name="da discurso"),
        ),
        migrations.AddField(
            model_name="tableguest",
            name="speech_member",
            field=models.ForeignKey(
                blank=True,
                help_text="Registro creado automáticamente en Cortejo nupcial › Discursos.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="events.weddingpartymember",
                verbose_name="registro en discursos",
            ),
        ),
    ]
