# Generated by Django 6.0.7 on 2026-07-24 18:51

from django.db import migrations, models


def split_name(apps, schema_editor):
    """Best-effort split of the old combined 'name' into first_name/last_name on
    the first space — imperfect for compound first/last names (e.g. 'Maria
    Gabriela Joa'), so guests should ideally be re-imported from the source
    Excel (which has real separate Nombre/Apellido columns) after this runs."""
    TableGuest = apps.get_model("events", "TableGuest")
    for guest in TableGuest.objects.all():
        parts = (guest.name or "").split(" ", 1)
        guest.first_name = parts[0]
        guest.last_name = parts[1] if len(parts) > 1 else ""
        guest.save(update_fields=["first_name", "last_name"])


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0011_tableguest_event_invita_sexo"),
    ]

    operations = [
        migrations.AddField(
            model_name="tableguest",
            name="dietary_restrictions",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="restricciones alimenticias",
            ),
        ),
        migrations.AddField(
            model_name="tableguest",
            name="family",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="familia"
            ),
        ),
        migrations.AddField(
            model_name="tableguest",
            name="first_name",
            field=models.CharField(default="", max_length=100, verbose_name="nombre"),
        ),
        migrations.AddField(
            model_name="tableguest",
            name="last_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="apellido"
            ),
        ),
        migrations.AddField(
            model_name="tableguest",
            name="main_dish",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="plato principal"
            ),
        ),
        migrations.AddField(
            model_name="tableguest",
            name="relationship",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="rol / parentesco"
            ),
        ),
        migrations.AddField(
            model_name="tableguest",
            name="rsvp",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="RSVP"
            ),
        ),
        migrations.AlterField(
            model_name="tableguest",
            name="notes",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="anotaciones"
            ),
        ),
        migrations.RunPython(split_name, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="tableguest",
            options={
                "ordering": ["order", "first_name", "last_name"],
                "verbose_name": "invitado",
                "verbose_name_plural": "invitados",
            },
        ),
        migrations.RemoveField(
            model_name="tableguest",
            name="name",
        ),
    ]
