# Generated by Django 6.0.7 on 2026-07-18 20:33

import apps.notes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.notes.models.event_file_upload_path,
                        verbose_name="archivo",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=150, verbose_name="título"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="subido el"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_files_uploaded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="subido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "archivo del evento",
                "verbose_name_plural": "archivos del evento",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="contenido")),
                ("pinned", models.BooleanField(default=False, verbose_name="fijada")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creada"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notes_written",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="autor",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "nota",
                "verbose_name_plural": "notas",
                "ordering": ["-pinned", "-created_at"],
            },
        ),
    ]
