# Generated by Django 6.0.7 on 2026-07-20 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="última modificación"
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="modificada por",
            ),
        ),
    ]
