# Generated by Django 6.0.7 on 2026-07-13 23:11

import apps.tasks.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="tarea")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Ej. Montaje, Logística, Decoración, Insumos",
                        max_length=100,
                        verbose_name="categoría",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha límite"
                    ),
                ),
                (
                    "due_time",
                    models.TimeField(blank=True, null=True, verbose_name="hora límite"),
                ),
                (
                    "requires_photo",
                    models.BooleanField(default=False, verbose_name="requiere foto"),
                ),
                (
                    "requires_document",
                    models.BooleanField(
                        default=False, verbose_name="requiere documento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_progreso", "En progreso"),
                            ("completada", "Completada"),
                            ("con_problema", "Con problema"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completada el"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_assigned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="encargado",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks_completed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="completada por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks_supervised",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="supervisor",
                    ),
                ),
            ],
            options={
                "verbose_name": "tarea",
                "verbose_name_plural": "tareas",
                "ordering": ["due_date", "due_time", "id"],
            },
        ),
        migrations.CreateModel(
            name="TaskEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.tasks.models.evidence_upload_path,
                        verbose_name="archivo",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="comentario"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="subido el"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="tasks.task",
                        verbose_name="tarea",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidences_uploaded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="subido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "evidencia",
                "verbose_name_plural": "evidencias",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
