# Generated by Django 6.0.7 on 2026-07-18 20:33

import apps.tasks.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="tarea")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Ej. Montaje, Logística, Decoración, Insumos",
                        max_length=100,
                        verbose_name="categoría",
                    ),
                ),
                (
                    "external_assignee_name",
                    models.CharField(
                        blank=True,
                        help_text="Nombre de un contacto (proveedor o cliente) que no tiene usuario ni ficha en el sistema",
                        max_length=150,
                        verbose_name="responsable externo",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha límite"
                    ),
                ),
                (
                    "due_time",
                    models.TimeField(blank=True, null=True, verbose_name="hora límite"),
                ),
                (
                    "requires_photo",
                    models.BooleanField(default=False, verbose_name="requiere foto"),
                ),
                (
                    "requires_video",
                    models.BooleanField(default=False, verbose_name="requiere video"),
                ),
                (
                    "requires_document",
                    models.BooleanField(
                        default=False, verbose_name="requiere documento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_progreso", "En progreso"),
                            ("completada", "Completada"),
                            ("con_problema", "Con problema"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora real en que se hizo la tarea; por defecto es ahora, pero se puede ajustar.",
                        null=True,
                        verbose_name="completada el",
                    ),
                ),
                (
                    "completion_recorded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Momento exacto en que quedó guardado en el sistema (no editable).",
                        null=True,
                        verbose_name="registrada en el sistema el",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_assigned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="encargado",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks_completed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="completada por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
                (
                    "itinerary_session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vincula esta tarea a un momento específico del itinerario (opcional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="events.eventsession",
                        verbose_name="momento del itinerario",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks_supervised",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="supervisor",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Proveedor registrado responsable de esta tarea, en vez de un usuario del sistema",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="vendors.vendor",
                        verbose_name="proveedor responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "tarea",
                "verbose_name_plural": "tareas",
                "ordering": ["due_date", "due_time", "id"],
            },
        ),
        migrations.CreateModel(
            name="TaskEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.tasks.models.evidence_upload_path,
                        verbose_name="archivo",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="comentario"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="subido el"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="tasks.task",
                        verbose_name="tarea",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidences_uploaded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="subido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "evidencia",
                "verbose_name_plural": "evidencias",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_progreso", "En progreso"),
                            ("completada", "Completada"),
                            ("con_problema", "Con problema"),
                        ],
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha del cambio"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="nota"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cambiado por",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="tasks.task",
                        verbose_name="tarea",
                    ),
                ),
            ],
            options={
                "verbose_name": "historial de estado",
                "verbose_name_plural": "historial de estados",
                "ordering": ["-changed_at"],
            },
        ),
    ]
