# Generated by Django 6.0.7 on 2026-07-20 00:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskstatushistory",
            name="changed_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="fecha del cambio"
            ),
        ),
    ]
