# Generated by Django 6.0.7 on 2026-07-23 18:00

from django.db import migrations, models


def backfill_is_guion(apps, schema_editor):
    """Tasks already linked to an itinerary moment were being shown with the
    'Guión' badge before it became its own editable field — preserve that."""
    Task = apps.get_model("tasks", "Task")
    Task.objects.filter(itinerary_session__isnull=False).update(is_guion=True)


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_taskstatushistory_changed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_guion",
            field=models.BooleanField(
                default=False,
                help_text="Marca si esta tarea forma parte del guión (minuto a minuto) del evento.",
                verbose_name="en el guión",
            ),
        ),
        migrations.RunPython(backfill_is_guion, migrations.RunPython.noop),
    ]
