# Generated by Django 6.0.7 on 2026-07-29 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0012_tableguest_split_name_and_fields"),
        ("tasks", "0003_task_is_guion"),
        ("vendors", "0004_backfill_vendor_payments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="chain_order",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="orden en la cadena"
            ),
        ),
        migrations.CreateModel(
            name="TaskChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creada"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_chains_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creada por",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_chains",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "cadena de tareas",
                "verbose_name_plural": "cadenas de tareas",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="chain",
            field=models.ForeignKey(
                blank=True,
                help_text="Agrupa esta tarea dentro de una secuencia ordenada (opcional).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="tasks.taskchain",
                verbose_name="cadena de tareas",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(("chain__isnull", False)),
                fields=("chain", "chain_order"),
                name="unique_chain_order_per_chain",
            ),
        ),
    ]
