# Generated by Django 6.0.7 on 2026-08-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_task_chain_order_taskchain_task_chain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_guion_cliente",
            field=models.BooleanField(
                default=False,
                help_text="Marca si esta tarea forma parte del guión que se entrega al cliente.",
                verbose_name="en el guión cliente",
            ),
        ),
    ]
