# Generated by Django 6.0.7 on 2026-07-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="date_format",
            field=models.CharField(
                choices=[
                    ("iso", "AAAA-MM-DD"),
                    ("dmy", "DD/MM/AAAA"),
                    ("mdy", "MM/DD/AAAA"),
                ],
                default="dmy",
                max_length=3,
                verbose_name="formato de fecha",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="date_show_weekday",
            field=models.BooleanField(
                default=False, verbose_name="mostrar día de la semana en las fechas"
            ),
        ),
    ]
