# Generated by Django 6.0.7 on 2026-08-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_company_date_format_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="iniciales",
            field=models.CharField(
                blank=True,
                help_text="Se usa en el reporte minuto a minuto para no mostrar el nombre completo. Ej. JCJ.",
                max_length=10,
                verbose_name="iniciales",
            ),
        ),
    ]
