# Generated by Django 6.0.7 on 2026-07-18 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nombre")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("espacio", "Espacio / Venue"),
                            ("banquete", "Banquete"),
                            ("flores", "Flores"),
                            ("musica", "Música"),
                            ("fotografia", "Fotografía / Video"),
                            ("licor", "Licor / Bebidas"),
                            ("mobiliario", "Mobiliario"),
                            ("transporte", "Transporte"),
                            ("decoracion", "Decoración"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=20,
                        verbose_name="categoría",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="contacto"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendors",
                        to="accounts.company",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "proveedor / espacio",
                "verbose_name_plural": "proveedores y espacios",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EventVendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="monto del contrato",
                    ),
                ),
                (
                    "deposit_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="anticipo pagado",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("cotizacion", "Cotización"),
                            ("confirmado", "Confirmado"),
                            ("pagado", "Pagado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="cotizacion",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_vendors",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_bookings",
                        to="vendors.vendor",
                        verbose_name="proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "proveedor del evento",
                "verbose_name_plural": "proveedores del evento",
                "ordering": ["-created_at"],
                "unique_together": {("event", "vendor")},
            },
        ),
    ]
