# Generated by Django 6.0.7 on 2026-07-20 02:20

import apps.vendors.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0002_vendorcategory_and_migrate_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventvendor",
            name="deposit_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Se recalcula automáticamente a partir de los abonos registrados.",
                max_digits=12,
                verbose_name="total abonado",
            ),
        ),
        migrations.CreateModel(
            name="VendorPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="fecha")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="monto"
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        help_text="Requerido cuando este abono completa el saldo del proveedor.",
                        null=True,
                        upload_to=apps.vendors.models.vendor_payment_document_upload_path,
                        verbose_name="documento",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="nota"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_payments_recorded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registrado por",
                    ),
                ),
                (
                    "event_vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="vendors.eventvendor",
                        verbose_name="proveedor del evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "abono a proveedor",
                "verbose_name_plural": "abonos a proveedores",
                "ordering": ["-date", "-id"],
            },
        ),
    ]
